    name: Bun CI

    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - main

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4

          - name: Set up Bun
            uses: oven-sh/setup-bun@v2
            with:
              bun-version: latest # Or specify a specific version like '1.2.0'

          - name: Install dependencies
            run: bun install

          - name: Run tests (example)
            run: bun test

          - name: Build project (example)
            run: bun run build
